# Generated by Django 5.1.3 on 2025-06-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=255, verbose_name='адрес')),
                ('time', models.CharField(max_length=255, verbose_name='время работы')),
                ('number', models.CharField(max_length=255, verbose_name='Номер горячей линии')),
                ('inn', models.CharField(max_length=255, verbose_name='ИНН')),
                ('ogrn', models.CharField(max_length=255, verbose_name='ОГРНИП')),
                ('ip', models.CharField(max_length=255, verbose_name='Юр. наименование')),
            ],
            options={
                'verbose_name': 'данные',
                'verbose_name_plural': 'Контактные данные',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='наименование')),
                ('url', models.CharField(max_length=255, verbose_name='ссылка')),
            ],
            options={
                'verbose_name': 'Социальные сети',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
    ]
