# Generated by Django 5.1.1 on 2025-06-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_remove_social_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=255, verbose_name='адрес')),
                ('time', models.CharField(max_length=255, verbose_name='время работы')),
                ('number', models.CharField(max_length=255, verbose_name='Номер горячей линии')),
                ('inn', models.CharField(max_length=255, verbose_name='ИНН')),
                ('ogrn', models.CharField(max_length=255, verbose_name='ОГРНИП')),
                ('ip', models.CharField(max_length=255, verbose_name='Юр. наименование')),
            ],
            options={
                'verbose_name': 'данные',
                'verbose_name_plural': 'Контактные данные',
            },
        ),
    ]
