# Generated by Django 5.1.1 on 2025-06-15 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotext',
            options={'verbose_name': 'текст', 'verbose_name_plural': 'Текст в первом блоке на главном экране'},
        ),
    ]
