# Generated by Django 5.1.3 on 2025-06-23 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_types_name', models.CharField(max_length=100)),
                ('body_type', models.CharField(choices=[('sedan', 'Седан'), ('crossover', 'Кроссовер'), ('jeep', 'Джип'), ('minibus', 'Микроавтобус'), ('truck', 'Грузовик')], default='sedan', max_length=20)),
            ],
            options={
                'verbose_name': 'Тип машины',
                'verbose_name_plural': 'Тип машин',
            },
        ),
        migrations.CreateModel(
            name='cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255, verbose_name='Название города')),
                ('distance_from_vladivostok', models.IntegerField(verbose_name='Расстояние от Владивостока, км')),
                ('delivery_time_days', models.IntegerField(verbose_name='Время в пути, ДО, в сутках')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'цвет',
                'verbose_name_plural': 'Цвета авто',
            },
        ),
        migrations.CreateModel(
            name='DriveTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'тип',
                'verbose_name_plural': 'Типы привода',
            },
        ),
        migrations.CreateModel(
            name='EngineTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'тип',
                'verbose_name_plural': 'Типы двигателя',
            },
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='все форматы(кроме svg) конвертируются в webp', upload_to='images/%Y/%m/%d/', verbose_name='изображение')),
            ],
            options={
                'verbose_name': 'фото',
                'verbose_name_plural': 'фото',
            },
        ),
        migrations.CreateModel(
            name='TransmissionTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'тип',
                'verbose_name_plural': 'Типы КПП',
            },
        ),
        migrations.CreateModel(
            name='car_delivery_prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('car_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.car_types', verbose_name='Тип_кузова')),
                ('city_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.cities', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Цена доставки',
                'verbose_name_plural': 'Цены доставки',
            },
        ),
        migrations.CreateModel(
            name='CarsKorea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Бренд')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('mileage', models.IntegerField(verbose_name='Пробег')),
                ('kuzov', models.CharField(max_length=50, verbose_name='Кузов')),
                ('engine_volume', models.IntegerField(verbose_name='Объем двигателя')),
                ('finish', models.CharField(max_length=50, verbose_name='Цена в валюте экспортера')),
                ('rubber', models.CharField(blank=True, choices=[('Левый руль', 'Левый руль'), ('Правый руль', 'Правый руль')], default='Левый руль', max_length=30, null=True, verbose_name='Руль')),
                ('country', models.CharField(choices=[('Япония', 'Япония'), ('Китай', 'Китай'), ('Корея', 'Корея')], max_length=250, verbose_name='Страна')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.colors', verbose_name='Цвет')),
                ('drive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.drivetypes', verbose_name='Тип привода')),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.enginetypes', verbose_name='Тип двигателя')),
                ('photos', models.ManyToManyField(blank=True, to='catalog.imagemodel', verbose_name='Фотографии авто')),
                ('transmission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.transmissiontypes', verbose_name='Тип КПП')),
            ],
            options={
                'verbose_name': 'Автомобили',
                'verbose_name_plural': 'Автомобили Корея',
            },
        ),
        migrations.CreateModel(
            name='CarsJapan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Бренд')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('mileage', models.IntegerField(verbose_name='Пробег')),
                ('kuzov', models.CharField(max_length=50, verbose_name='Кузов')),
                ('engine_volume', models.IntegerField(verbose_name='Объем двигателя')),
                ('finish', models.CharField(max_length=50, verbose_name='Цена в валюте экспортера')),
                ('rubber', models.CharField(blank=True, choices=[('Левый руль', 'Левый руль'), ('Правый руль', 'Правый руль')], default='Левый руль', max_length=30, null=True, verbose_name='Руль')),
                ('country', models.CharField(choices=[('Япония', 'Япония'), ('Китай', 'Китай'), ('Корея', 'Корея')], max_length=250, verbose_name='Страна')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.colors', verbose_name='Цвет')),
                ('drive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.drivetypes', verbose_name='Тип привода')),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.enginetypes', verbose_name='Тип двигателя')),
                ('photos', models.ManyToManyField(blank=True, to='catalog.imagemodel', verbose_name='Фотографии авто')),
                ('transmission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.transmissiontypes', verbose_name='Тип КПП')),
            ],
            options={
                'verbose_name': 'Автомобили',
                'verbose_name_plural': 'Автомобили Япония',
            },
        ),
        migrations.CreateModel(
            name='CarsChina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Бренд')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('mileage', models.IntegerField(verbose_name='Пробег')),
                ('kuzov', models.CharField(max_length=50, verbose_name='Кузов')),
                ('engine_volume', models.IntegerField(verbose_name='Объем двигателя')),
                ('finish', models.CharField(max_length=50, verbose_name='Цена в валюте экспортера')),
                ('rubber', models.CharField(blank=True, choices=[('Левый руль', 'Левый руль'), ('Правый руль', 'Правый руль')], default='Левый руль', max_length=30, null=True, verbose_name='Руль')),
                ('country', models.CharField(choices=[('Япония', 'Япония'), ('Китай', 'Китай'), ('Корея', 'Корея')], max_length=250, verbose_name='Страна')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.colors', verbose_name='Цвет')),
                ('drive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.drivetypes', verbose_name='Тип привода')),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.enginetypes', verbose_name='Тип двигателя')),
                ('photos', models.ManyToManyField(blank=True, to='catalog.imagemodel', verbose_name='Фотографии авто')),
                ('transmission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.transmissiontypes', verbose_name='Тип КПП')),
            ],
            options={
                'verbose_name': 'Автомобили',
                'verbose_name_plural': 'Автомобили Китай',
            },
        ),
    ]
