# Generated by Django 5.1.3 on 2025-06-24 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='delivery_time_days',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='distance_from_vladivostok',
        ),
    ]
