# Generated by Django 5.1.1 on 2025-06-15 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_cars_delete_abstractauccars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='engine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='catalog.enginetypes', verbose_name='Тип двигателя'),
            preserve_default=False,
        ),
    ]
