# Generated by Django 5.1.3 on 2025-06-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_cities_delivery_time_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_types',
            name='body_type',
            field=models.CharField(choices=[('key-car', 'Кей-кар'), ('sedan', 'Седан'), ('sedan', 'Седан'), ('crossover', 'Кроссовер'), ('jeep', 'Джип'), ('minibus', 'Минивэн')], default='sedan', max_length=20),
        ),
    ]
