# Generated by Django 5.1.1 on 2025-06-15 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_cars_engine'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cars',
            new_name='CarsJapan',
        ),
    ]
