# Generated by Django 5.1.1 on 2025-06-15 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_cars_carsjapan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carsjapan',
            options={'verbose_name': 'Автомобили', 'verbose_name_plural': 'Автомобили Япония'},
        ),
    ]
