# Generated by Django 5.1.4 on 2025-06-18 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_carsjapan_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='car_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_types_name', models.CharField(max_length=100)),
                ('body_type', models.CharField(choices=[('sedan', 'Седан'), ('crossover', 'Кроссовер'), ('jeep', 'Джип'), ('minibus', 'Микроавтобус'), ('truck', 'Грузовик')], default='sedan', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255, verbose_name='Название города')),
                ('distance_from_vladivostok', models.IntegerField(verbose_name='Расстояние от Владивостока, км')),
                ('delivery_time_days', models.IntegerField(verbose_name='Время в пути, ДО, в сутках')),
            ],
        ),
        migrations.CreateModel(
            name='car_delivery_prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('car_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.car_types', verbose_name='Город')),
                ('city_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.cities', verbose_name='Город')),
            ],
        ),
    ]
